version: "3.8"
services:
  mysql:
    container_name: postgres-minions
    build:
      context: ./
      dockerfile: postgres-minions-test
    image: postgres-minions:1.0
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  demo:
    container_name: demo
    build:
      context: ./
      dockerfile: demo-test
    image: demo:1.0
    ports:
      - "8080:8080"
    links:
      - mysql:mysql-minions.com