version: "3.8"
services:
  mysql:
    container_name: mysql-minions
    build:
      context: ./
      dockerfile: mysql-minions-test
    image: mysql-minions:1.0
    environment:
      - "MYSQL_ROOT_PASSWORD=root123"
    ports:
      - "3306:3306"