version: "3.8"
services:
  postgres:
    container_name: postgres-minions
    image: postgres:12.4
    hostname: postgres-minions
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=minions"
      - "POSTGRES_USER=minions"
    ports:
      - "5432:5432"
    networks:
      minions:
        ipv4_address: 172.31.0.12

  demo:
    container_name: demo
    build:
      context: ./
      dockerfile: demo-test
    image: demo:1.0
    hostname: demo
    ports:
      - "8080:8080"
    links:
      - postgres:postgres-minions.com
      - mongo:mongo-minions.com
      - redis:redis-minions.com
      - zookeeper:zookeeper-minions.com
      - kafka:kafka-minions.com
    networks:
      minions:
        ipv4_address: 172.31.0.13

  kafka-consumer:
    container_name: kafka-consumer
    build:
      context: ./
      dockerfile: kafka-consumer-test
    image: kafka-consumer:1.0
    hostname: kafka-consumer
    ports:
      - "8081:8081"
    links:
      - postgres:postgres-minions.com
      - mongo:mongo-minions.com
      - redis:redis-minions.com
      - zookeeper:zookeeper-minions.com
      - kafka:kafka-minions.com
    networks:
      minions:
        ipv4_address: 172.31.0.18

  spider:
    container_name: spider-minions
    build:
      context: .
      dockerfile: spiders/Dockerfile
    image: spider-minions:1.0
    hostname: spider
    links:
      - kafka:kafka-minions.com

  mongo:
    container_name: mongo-minions
    image: mongo:4.4.0
    hostname: mongo-minions
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
    ports:
      - "27017:27017"
    networks:
      minions:
        ipv4_address: 172.31.0.14

  redis:
    container_name: redis-minions
    image: redis:6.0.6
    hostname: redis-minions
    ports:
      - 6379:6379
    command:
      redis-server --requirepass redis --appendonly yes
    networks:
      minions:
        ipv4_address: 172.31.0.15

  zookeeper:
    container_name: zookeeper-minions
    image: zookeeper:3.5.8
    hostname: zookeeper-minions
    ports:
      - "2181:2181"
    networks:
      minions:
        ipv4_address: 172.31.0.16

  kafka:
    container_name: kafka-minions
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka-minions
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeeper
    networks:
      minions:
        ipv4_address: 172.31.0.17

networks:
  minions:
    external:
      name: minions