version: "3.8"
services:
  postgres:
    container_name: postgres-minions
    build:
      context: ./
      dockerfile: postgres-minions-test
    image: postgres-minions:1.0
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  mongo:
    container_name: mongo-minions
    image: mongo:4.4.0
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
    ports:
      - "27017:27017"

  redis:
    container_name: redis-minions
    image: redis:6.0.6
    ports:
      - 6379:6379
    command:
      redis-server --requirepass redis --appendonly yes

  zookeeper:
    container_name: zookeeper--minions
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-minions
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeeper

