version: "3.8"
services:
  postgres:
    container_name: minions-postgres
    image: postgres:13.3-alpine
    hostname: minions-postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=minions"
      - "POSTGRES_USER=minions"
    ports:
      - "5432:5432"
    networks:
      minions:
        ipv4_address: 172.31.0.12

  demo:
    container_name: demo
    build:
      context: ./
      dockerfile: demo-test
    image: demo:1.0
    hostname: demo
    ports:
      - "8080:8080"
    links:
      - postgres:postgres.minions.com
      - mongo:mongo.minions.com
      - redis:redis.minions.com
      - zookeeper:zookeeper.minions.com
      - kafka:kafka.minions.com
    networks:
      minions:
        ipv4_address: 172.31.0.13

  mongo:
    container_name: minions-mongo
    image: mongo:4.4.6
    hostname: minions-mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
    ports:
      - "27017:27017"
    networks:
      minions:
        ipv4_address: 172.31.0.14

  redis:
    container_name: minions-redis
    image: redis:6.2.3-alpine
    hostname: minions-redis
    ports:
      - 6379:6379
    command:
      redis-server --requirepass redis --appendonly yes
    networks:
      minions:
        ipv4_address: 172.31.0.15

  zookeeper:
    container_name: minions-zookeeper
    image: zookeeper:3.5.9
    hostname: minions-zookeeper
    ports:
      - "2181:2181"
    networks:
      minions:
        ipv4_address: 172.31.0.16

  kafka:
    container_name: minions-kafka
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: minions-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.0.17
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper:zookeeper
    networks:
      minions:
        ipv4_address: 172.31.0.17

  kafka-consumer:
    container_name: kafka-consumer
    build:
      context: ./
      dockerfile: kafka-consumer-test
    image: kafka-consumer:1.0
    hostname: kafka-consumer
    ports:
      - "8081:8081"
    links:
      - postgres:postgres.minions.com
      - mongo:mongo.minions.com
      - redis:redis.minions.com
      - zookeeper:zookeeper.minions.com
      - kafka:kafka.minions.com
      - minions-spider:spider.minions.com
    networks:
      minions:
        ipv4_address: 172.31.0.18

  minions-spider:
    container_name: minions-spider
    build:
      context: ./spiders
      dockerfile: ./Dockerfile
    image: spider-minions:1.0
    hostname: spider-minions
    ports:
      - "6800:6800"
    links:
      - kafka:kafka.minions.com
      - mongo:mongo.minions.com
    networks:
      minions:
        ipv4_address: 172.31.0.19

networks:
  minions:
    external:
      name: minions
