version: "3.8"
services:
  postgres:
    container_name: minions-postgres
    image: postgres:13.4-alpine
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=minions"
      - "POSTGRES_USER=minions"
    ports:
      - "5432:5432"

  mongo:
    container_name: minions-mongo
    image: mongo:5.0.2-focal
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
    ports:
      - "27017:27017"

  redis:
    container_name: minions-redis
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    command:
      redis-server --requirepass redis --appendonly yes

  zookeeper:
    container_name: minions-zookeeper
    image: zookeeper:3.5.9
    ports:
      - "2181:2181"

  kafka:
    container_name: minions-kafka
    image: wurstmeister/kafka:2.13-2.7.0
    expose:
      - 9999
    ports:
      - 9092:9092
      - 9999:9999
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9999"
      JMX_PORT: 9999
    links:
      - zookeeper:zookeeper

  nacos:
    container_name: minions-nacos
    image: nacos/nacos-server:2.0.3-slim
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"

  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: minions-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  logstash:
    image: logstash:7.12.1
    container_name: minions-logstash
    volumes:
      - "./logstash.conf:/usr/share/logstash/config/logstash.conf:ro"
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
  kibana:
    image: kibana:7.12.1
    container_name: minions-kibana
    volumes:
      - "./kibana.yaml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch

  skywalking-oap:
    image: apache/skywalking-oap-server:8.7.0-es7
    container_name: minions-skywalking-oap
    ports:
      - 10800:10800
      - 11800:11800
      - 12800:12800
    environment:
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch

  skywalking-ui:
    image: apache/skywalking-ui:8.7.0
    container_name: minions-skywalking-ui
    ports:
      - 8080:8080
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap:oap



