version: "3.8"
services:
  postgres:
    container_name: postgres-minions
    build:
      context: ./
      dockerfile: postgres-minions-test
    image: postgres-minions:1.0
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"