version: "3.8"
services:
  postgres:
    container_name: minions-postgres
    image: postgres:13.3-alpine
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=minions"
      - "POSTGRES_USER=minions"
    ports:
      - "5432:5432"

  mongo:
    container_name: minions-mongo
    image: mongo:5.0.1-focal
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=mongo"
    ports:
      - "27017:27017"

  redis:
    container_name: minions-redis
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    command:
      redis-server --requirepass redis --appendonly yes

  zookeeper:
    container_name: minions-zookeeper
    image: zookeeper:3.5.9
    ports:
      - "2181:2181"

  kafka:
    container_name: minions-kafka
    image: wurstmeister/kafka:2.13-2.6.0
    expose:
      - 9999
    ports:
      - 9092:9092
      - 9999:9999
    environment:
      KAFKA_ADVERTISED_HOST_NAME: korov-linux.org
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=9999"
      JMX_PORT: 9999
    links:
      - zookeeper:zookeeper

#  jobmanager:
#    image: flink:scala_2.12-java11
#    container_name: flink-jobmanager-minions
#    expose:
#      - "6123"
#    ports:
#      - "18081:8081"
#    command: jobmanager
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#  taskmanager:
#    image: flink:scala_2.12-java11
#    container_name: flink-taskmanager-minions
#    expose:
#      - "6121"
#      - "6122"
#    command: taskmanager
#    links:
#      - jobmanager:jobmanager
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager

