server:
  port: 8080

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

mybatis:
  type-aliases-package: org.minions.common.moedel.demo
  mapper-locations:
    - classpath:mapper/*Mapper.xml

spring:
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minions?currentSchema=demo
    username: minions
    password: postgres
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: minions-demo

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/test