server:
  port: 8081

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minions?currentSchema=demo
    username: minions
    password: postgres
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: minions-demo
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: group-dev

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/test