package org.minions.kafka.mapper;

import org.minions.common.model.kafka.HeroInfoModel;

public interface HeroInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    int deleteByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    int insert(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    int insertSelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    HeroInfoModel selectByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    int updateByPrimaryKeySelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 19:51:28 CST 2020
     */
    int updateByPrimaryKey(HeroInfoModel record);
}