package org.minions.kafka.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.minions.common.model.kafka.HeroWeaponModel;
import org.minions.common.model.kafka.HeroWeaponModelExample;

public interface HeroWeaponModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    long countByExample(HeroWeaponModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int deleteByExample(HeroWeaponModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int deleteByPrimaryKey(Integer weaponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int insert(HeroWeaponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int insertSelective(HeroWeaponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    List<HeroWeaponModel> selectByExample(HeroWeaponModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    HeroWeaponModel selectByPrimaryKey(Integer weaponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") HeroWeaponModel record, @Param("example") HeroWeaponModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByExample(@Param("record") HeroWeaponModel record, @Param("example") HeroWeaponModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByPrimaryKeySelective(HeroWeaponModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByPrimaryKey(HeroWeaponModel record);
}