package org.minions.kafka.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.minions.common.model.kafka.HeroInfoModel;
import org.minions.common.model.kafka.HeroInfoModelExample;

public interface HeroInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    long countByExample(HeroInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int deleteByExample(HeroInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int deleteByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int insert(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int insertSelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    List<HeroInfoModel> selectByExample(HeroInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    HeroInfoModel selectByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByExampleSelective(@Param("record") HeroInfoModel record, @Param("example") HeroInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByExample(@Param("record") HeroInfoModel record, @Param("example") HeroInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByPrimaryKeySelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    int updateByPrimaryKey(HeroInfoModel record);
}