package org.minions.kafka.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.minions.common.model.kafka.HeroInfoModel;

@Mapper
public interface HeroInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    int deleteByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    int insert(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    int insertSelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    HeroInfoModel selectByPrimaryKey(Integer heroId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    int updateByPrimaryKeySelective(HeroInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Sun Sep 13 17:22:56 CST 2020
     */
    int updateByPrimaryKey(HeroInfoModel record);
}