package org.minions.common.model.kafka;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HeroInfoModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public HeroInfoModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHeroIdIsNull() {
            addCriterion("hero_id is null");
            return (Criteria) this;
        }

        public Criteria andHeroIdIsNotNull() {
            addCriterion("hero_id is not null");
            return (Criteria) this;
        }

        public Criteria andHeroIdEqualTo(Integer value) {
            addCriterion("hero_id =", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdNotEqualTo(Integer value) {
            addCriterion("hero_id <>", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdGreaterThan(Integer value) {
            addCriterion("hero_id >", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hero_id >=", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdLessThan(Integer value) {
            addCriterion("hero_id <", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdLessThanOrEqualTo(Integer value) {
            addCriterion("hero_id <=", value, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdIn(List<Integer> values) {
            addCriterion("hero_id in", values, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdNotIn(List<Integer> values) {
            addCriterion("hero_id not in", values, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdBetween(Integer value1, Integer value2) {
            addCriterion("hero_id between", value1, value2, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hero_id not between", value1, value2, "heroId");
            return (Criteria) this;
        }

        public Criteria andHeroNameIsNull() {
            addCriterion("hero_name is null");
            return (Criteria) this;
        }

        public Criteria andHeroNameIsNotNull() {
            addCriterion("hero_name is not null");
            return (Criteria) this;
        }

        public Criteria andHeroNameEqualTo(String value) {
            addCriterion("hero_name =", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameNotEqualTo(String value) {
            addCriterion("hero_name <>", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameGreaterThan(String value) {
            addCriterion("hero_name >", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameGreaterThanOrEqualTo(String value) {
            addCriterion("hero_name >=", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameLessThan(String value) {
            addCriterion("hero_name <", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameLessThanOrEqualTo(String value) {
            addCriterion("hero_name <=", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameLike(String value) {
            addCriterion("hero_name like", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameNotLike(String value) {
            addCriterion("hero_name not like", value, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameIn(List<String> values) {
            addCriterion("hero_name in", values, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameNotIn(List<String> values) {
            addCriterion("hero_name not in", values, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameBetween(String value1, String value2) {
            addCriterion("hero_name between", value1, value2, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNameNotBetween(String value1, String value2) {
            addCriterion("hero_name not between", value1, value2, "heroName");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameIsNull() {
            addCriterion("hero_nickname is null");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameIsNotNull() {
            addCriterion("hero_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameEqualTo(String value) {
            addCriterion("hero_nickname =", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameNotEqualTo(String value) {
            addCriterion("hero_nickname <>", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameGreaterThan(String value) {
            addCriterion("hero_nickname >", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("hero_nickname >=", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameLessThan(String value) {
            addCriterion("hero_nickname <", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameLessThanOrEqualTo(String value) {
            addCriterion("hero_nickname <=", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameLike(String value) {
            addCriterion("hero_nickname like", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameNotLike(String value) {
            addCriterion("hero_nickname not like", value, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameIn(List<String> values) {
            addCriterion("hero_nickname in", values, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameNotIn(List<String> values) {
            addCriterion("hero_nickname not in", values, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameBetween(String value1, String value2) {
            addCriterion("hero_nickname between", value1, value2, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroNicknameNotBetween(String value1, String value2) {
            addCriterion("hero_nickname not between", value1, value2, "heroNickname");
            return (Criteria) this;
        }

        public Criteria andHeroImgIsNull() {
            addCriterion("hero_img is null");
            return (Criteria) this;
        }

        public Criteria andHeroImgIsNotNull() {
            addCriterion("hero_img is not null");
            return (Criteria) this;
        }

        public Criteria andHeroImgEqualTo(String value) {
            addCriterion("hero_img =", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgNotEqualTo(String value) {
            addCriterion("hero_img <>", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgGreaterThan(String value) {
            addCriterion("hero_img >", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgGreaterThanOrEqualTo(String value) {
            addCriterion("hero_img >=", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgLessThan(String value) {
            addCriterion("hero_img <", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgLessThanOrEqualTo(String value) {
            addCriterion("hero_img <=", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgLike(String value) {
            addCriterion("hero_img like", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgNotLike(String value) {
            addCriterion("hero_img not like", value, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgIn(List<String> values) {
            addCriterion("hero_img in", values, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgNotIn(List<String> values) {
            addCriterion("hero_img not in", values, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgBetween(String value1, String value2) {
            addCriterion("hero_img between", value1, value2, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroImgNotBetween(String value1, String value2) {
            addCriterion("hero_img not between", value1, value2, "heroImg");
            return (Criteria) this;
        }

        public Criteria andHeroTypeIsNull() {
            addCriterion("hero_type is null");
            return (Criteria) this;
        }

        public Criteria andHeroTypeIsNotNull() {
            addCriterion("hero_type is not null");
            return (Criteria) this;
        }

        public Criteria andHeroTypeEqualTo(String value) {
            addCriterion("hero_type =", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeNotEqualTo(String value) {
            addCriterion("hero_type <>", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeGreaterThan(String value) {
            addCriterion("hero_type >", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeGreaterThanOrEqualTo(String value) {
            addCriterion("hero_type >=", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeLessThan(String value) {
            addCriterion("hero_type <", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeLessThanOrEqualTo(String value) {
            addCriterion("hero_type <=", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeLike(String value) {
            addCriterion("hero_type like", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeNotLike(String value) {
            addCriterion("hero_type not like", value, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeIn(List<String> values) {
            addCriterion("hero_type in", values, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeNotIn(List<String> values) {
            addCriterion("hero_type not in", values, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeBetween(String value1, String value2) {
            addCriterion("hero_type between", value1, value2, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroTypeNotBetween(String value1, String value2) {
            addCriterion("hero_type not between", value1, value2, "heroType");
            return (Criteria) this;
        }

        public Criteria andHeroStoryIsNull() {
            addCriterion("hero_story is null");
            return (Criteria) this;
        }

        public Criteria andHeroStoryIsNotNull() {
            addCriterion("hero_story is not null");
            return (Criteria) this;
        }

        public Criteria andHeroStoryEqualTo(String value) {
            addCriterion("hero_story =", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryNotEqualTo(String value) {
            addCriterion("hero_story <>", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryGreaterThan(String value) {
            addCriterion("hero_story >", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryGreaterThanOrEqualTo(String value) {
            addCriterion("hero_story >=", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryLessThan(String value) {
            addCriterion("hero_story <", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryLessThanOrEqualTo(String value) {
            addCriterion("hero_story <=", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryLike(String value) {
            addCriterion("hero_story like", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryNotLike(String value) {
            addCriterion("hero_story not like", value, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryIn(List<String> values) {
            addCriterion("hero_story in", values, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryNotIn(List<String> values) {
            addCriterion("hero_story not in", values, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryBetween(String value1, String value2) {
            addCriterion("hero_story between", value1, value2, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroStoryNotBetween(String value1, String value2) {
            addCriterion("hero_story not between", value1, value2, "heroStory");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsIsNull() {
            addCriterion("hero_levels is null");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsIsNotNull() {
            addCriterion("hero_levels is not null");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsEqualTo(String value) {
            addCriterion("hero_levels =", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsNotEqualTo(String value) {
            addCriterion("hero_levels <>", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsGreaterThan(String value) {
            addCriterion("hero_levels >", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsGreaterThanOrEqualTo(String value) {
            addCriterion("hero_levels >=", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsLessThan(String value) {
            addCriterion("hero_levels <", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsLessThanOrEqualTo(String value) {
            addCriterion("hero_levels <=", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsLike(String value) {
            addCriterion("hero_levels like", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsNotLike(String value) {
            addCriterion("hero_levels not like", value, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsIn(List<String> values) {
            addCriterion("hero_levels in", values, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsNotIn(List<String> values) {
            addCriterion("hero_levels not in", values, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsBetween(String value1, String value2) {
            addCriterion("hero_levels between", value1, value2, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroLevelsNotBetween(String value1, String value2) {
            addCriterion("hero_levels not between", value1, value2, "heroLevels");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceIsNull() {
            addCriterion("hero_gold_price is null");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceIsNotNull() {
            addCriterion("hero_gold_price is not null");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceEqualTo(BigDecimal value) {
            addCriterion("hero_gold_price =", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceNotEqualTo(BigDecimal value) {
            addCriterion("hero_gold_price <>", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceGreaterThan(BigDecimal value) {
            addCriterion("hero_gold_price >", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_gold_price >=", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceLessThan(BigDecimal value) {
            addCriterion("hero_gold_price <", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_gold_price <=", value, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceIn(List<BigDecimal> values) {
            addCriterion("hero_gold_price in", values, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceNotIn(List<BigDecimal> values) {
            addCriterion("hero_gold_price not in", values, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_gold_price between", value1, value2, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroGoldPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_gold_price not between", value1, value2, "heroGoldPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceIsNull() {
            addCriterion("hero_ticket_price is null");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceIsNotNull() {
            addCriterion("hero_ticket_price is not null");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceEqualTo(BigDecimal value) {
            addCriterion("hero_ticket_price =", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceNotEqualTo(BigDecimal value) {
            addCriterion("hero_ticket_price <>", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceGreaterThan(BigDecimal value) {
            addCriterion("hero_ticket_price >", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_ticket_price >=", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceLessThan(BigDecimal value) {
            addCriterion("hero_ticket_price <", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_ticket_price <=", value, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceIn(List<BigDecimal> values) {
            addCriterion("hero_ticket_price in", values, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceNotIn(List<BigDecimal> values) {
            addCriterion("hero_ticket_price not in", values, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_ticket_price between", value1, value2, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroTicketPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_ticket_price not between", value1, value2, "heroTicketPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceIsNull() {
            addCriterion("hero_diamond_price is null");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceIsNotNull() {
            addCriterion("hero_diamond_price is not null");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceEqualTo(BigDecimal value) {
            addCriterion("hero_diamond_price =", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceNotEqualTo(BigDecimal value) {
            addCriterion("hero_diamond_price <>", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceGreaterThan(BigDecimal value) {
            addCriterion("hero_diamond_price >", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_diamond_price >=", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceLessThan(BigDecimal value) {
            addCriterion("hero_diamond_price <", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hero_diamond_price <=", value, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceIn(List<BigDecimal> values) {
            addCriterion("hero_diamond_price in", values, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceNotIn(List<BigDecimal> values) {
            addCriterion("hero_diamond_price not in", values, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_diamond_price between", value1, value2, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andHeroDiamondPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hero_diamond_price not between", value1, value2, "heroDiamondPrice");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillIsNull() {
            addCriterion("recommend_summoner_skill is null");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillIsNotNull() {
            addCriterion("recommend_summoner_skill is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillEqualTo(String value) {
            addCriterion("recommend_summoner_skill =", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillNotEqualTo(String value) {
            addCriterion("recommend_summoner_skill <>", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillGreaterThan(String value) {
            addCriterion("recommend_summoner_skill >", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillGreaterThanOrEqualTo(String value) {
            addCriterion("recommend_summoner_skill >=", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillLessThan(String value) {
            addCriterion("recommend_summoner_skill <", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillLessThanOrEqualTo(String value) {
            addCriterion("recommend_summoner_skill <=", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillLike(String value) {
            addCriterion("recommend_summoner_skill like", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillNotLike(String value) {
            addCriterion("recommend_summoner_skill not like", value, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillIn(List<String> values) {
            addCriterion("recommend_summoner_skill in", values, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillNotIn(List<String> values) {
            addCriterion("recommend_summoner_skill not in", values, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillBetween(String value1, String value2) {
            addCriterion("recommend_summoner_skill between", value1, value2, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillNotBetween(String value1, String value2) {
            addCriterion("recommend_summoner_skill not between", value1, value2, "recommendSummonerSkill");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsIsNull() {
            addCriterion("rec_inscriptions is null");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsIsNotNull() {
            addCriterion("rec_inscriptions is not null");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsEqualTo(String value) {
            addCriterion("rec_inscriptions =", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsNotEqualTo(String value) {
            addCriterion("rec_inscriptions <>", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsGreaterThan(String value) {
            addCriterion("rec_inscriptions >", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsGreaterThanOrEqualTo(String value) {
            addCriterion("rec_inscriptions >=", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsLessThan(String value) {
            addCriterion("rec_inscriptions <", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsLessThanOrEqualTo(String value) {
            addCriterion("rec_inscriptions <=", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsLike(String value) {
            addCriterion("rec_inscriptions like", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsNotLike(String value) {
            addCriterion("rec_inscriptions not like", value, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsIn(List<String> values) {
            addCriterion("rec_inscriptions in", values, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsNotIn(List<String> values) {
            addCriterion("rec_inscriptions not in", values, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsBetween(String value1, String value2) {
            addCriterion("rec_inscriptions between", value1, value2, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andRecInscriptionsNotBetween(String value1, String value2) {
            addCriterion("rec_inscriptions not between", value1, value2, "recInscriptions");
            return (Criteria) this;
        }

        public Criteria andSkinImgsIsNull() {
            addCriterion("skin_imgs is null");
            return (Criteria) this;
        }

        public Criteria andSkinImgsIsNotNull() {
            addCriterion("skin_imgs is not null");
            return (Criteria) this;
        }

        public Criteria andSkinImgsEqualTo(String value) {
            addCriterion("skin_imgs =", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsNotEqualTo(String value) {
            addCriterion("skin_imgs <>", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsGreaterThan(String value) {
            addCriterion("skin_imgs >", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsGreaterThanOrEqualTo(String value) {
            addCriterion("skin_imgs >=", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsLessThan(String value) {
            addCriterion("skin_imgs <", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsLessThanOrEqualTo(String value) {
            addCriterion("skin_imgs <=", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsLike(String value) {
            addCriterion("skin_imgs like", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsNotLike(String value) {
            addCriterion("skin_imgs not like", value, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsIn(List<String> values) {
            addCriterion("skin_imgs in", values, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsNotIn(List<String> values) {
            addCriterion("skin_imgs not in", values, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsBetween(String value1, String value2) {
            addCriterion("skin_imgs between", value1, value2, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andSkinImgsNotBetween(String value1, String value2) {
            addCriterion("skin_imgs not between", value1, value2, "skinImgs");
            return (Criteria) this;
        }

        public Criteria andBigImgIsNull() {
            addCriterion("big_img is null");
            return (Criteria) this;
        }

        public Criteria andBigImgIsNotNull() {
            addCriterion("big_img is not null");
            return (Criteria) this;
        }

        public Criteria andBigImgEqualTo(String value) {
            addCriterion("big_img =", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgNotEqualTo(String value) {
            addCriterion("big_img <>", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgGreaterThan(String value) {
            addCriterion("big_img >", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgGreaterThanOrEqualTo(String value) {
            addCriterion("big_img >=", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgLessThan(String value) {
            addCriterion("big_img <", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgLessThanOrEqualTo(String value) {
            addCriterion("big_img <=", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgLike(String value) {
            addCriterion("big_img like", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgNotLike(String value) {
            addCriterion("big_img not like", value, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgIn(List<String> values) {
            addCriterion("big_img in", values, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgNotIn(List<String> values) {
            addCriterion("big_img not in", values, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgBetween(String value1, String value2) {
            addCriterion("big_img between", value1, value2, "bigImg");
            return (Criteria) this;
        }

        public Criteria andBigImgNotBetween(String value1, String value2) {
            addCriterion("big_img not between", value1, value2, "bigImg");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroIsNull() {
            addCriterion("history_intro is null");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroIsNotNull() {
            addCriterion("history_intro is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroEqualTo(String value) {
            addCriterion("history_intro =", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroNotEqualTo(String value) {
            addCriterion("history_intro <>", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroGreaterThan(String value) {
            addCriterion("history_intro >", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroGreaterThanOrEqualTo(String value) {
            addCriterion("history_intro >=", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroLessThan(String value) {
            addCriterion("history_intro <", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroLessThanOrEqualTo(String value) {
            addCriterion("history_intro <=", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroLike(String value) {
            addCriterion("history_intro like", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroNotLike(String value) {
            addCriterion("history_intro not like", value, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroIn(List<String> values) {
            addCriterion("history_intro in", values, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroNotIn(List<String> values) {
            addCriterion("history_intro not in", values, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroBetween(String value1, String value2) {
            addCriterion("history_intro between", value1, value2, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andHistoryIntroNotBetween(String value1, String value2) {
            addCriterion("history_intro not between", value1, value2, "historyIntro");
            return (Criteria) this;
        }

        public Criteria andSkillTipsIsNull() {
            addCriterion("skill_tips is null");
            return (Criteria) this;
        }

        public Criteria andSkillTipsIsNotNull() {
            addCriterion("skill_tips is not null");
            return (Criteria) this;
        }

        public Criteria andSkillTipsEqualTo(String value) {
            addCriterion("skill_tips =", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsNotEqualTo(String value) {
            addCriterion("skill_tips <>", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsGreaterThan(String value) {
            addCriterion("skill_tips >", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsGreaterThanOrEqualTo(String value) {
            addCriterion("skill_tips >=", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsLessThan(String value) {
            addCriterion("skill_tips <", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsLessThanOrEqualTo(String value) {
            addCriterion("skill_tips <=", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsLike(String value) {
            addCriterion("skill_tips like", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsNotLike(String value) {
            addCriterion("skill_tips not like", value, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsIn(List<String> values) {
            addCriterion("skill_tips in", values, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsNotIn(List<String> values) {
            addCriterion("skill_tips not in", values, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsBetween(String value1, String value2) {
            addCriterion("skill_tips between", value1, value2, "skillTips");
            return (Criteria) this;
        }

        public Criteria andSkillTipsNotBetween(String value1, String value2) {
            addCriterion("skill_tips not between", value1, value2, "skillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsIsNull() {
            addCriterion("recommend_summoner_skill_tips is null");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsIsNotNull() {
            addCriterion("recommend_summoner_skill_tips is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsEqualTo(String value) {
            addCriterion("recommend_summoner_skill_tips =", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsNotEqualTo(String value) {
            addCriterion("recommend_summoner_skill_tips <>", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsGreaterThan(String value) {
            addCriterion("recommend_summoner_skill_tips >", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsGreaterThanOrEqualTo(String value) {
            addCriterion("recommend_summoner_skill_tips >=", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsLessThan(String value) {
            addCriterion("recommend_summoner_skill_tips <", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsLessThanOrEqualTo(String value) {
            addCriterion("recommend_summoner_skill_tips <=", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsLike(String value) {
            addCriterion("recommend_summoner_skill_tips like", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsNotLike(String value) {
            addCriterion("recommend_summoner_skill_tips not like", value, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsIn(List<String> values) {
            addCriterion("recommend_summoner_skill_tips in", values, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsNotIn(List<String> values) {
            addCriterion("recommend_summoner_skill_tips not in", values, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsBetween(String value1, String value2) {
            addCriterion("recommend_summoner_skill_tips between", value1, value2, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andRecommendSummonerSkillTipsNotBetween(String value1, String value2) {
            addCriterion("recommend_summoner_skill_tips not between", value1, value2, "recommendSummonerSkillTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsIsNull() {
            addCriterion("hero_tips is null");
            return (Criteria) this;
        }

        public Criteria andHeroTipsIsNotNull() {
            addCriterion("hero_tips is not null");
            return (Criteria) this;
        }

        public Criteria andHeroTipsEqualTo(String value) {
            addCriterion("hero_tips =", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsNotEqualTo(String value) {
            addCriterion("hero_tips <>", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsGreaterThan(String value) {
            addCriterion("hero_tips >", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsGreaterThanOrEqualTo(String value) {
            addCriterion("hero_tips >=", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsLessThan(String value) {
            addCriterion("hero_tips <", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsLessThanOrEqualTo(String value) {
            addCriterion("hero_tips <=", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsLike(String value) {
            addCriterion("hero_tips like", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsNotLike(String value) {
            addCriterion("hero_tips not like", value, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsIn(List<String> values) {
            addCriterion("hero_tips in", values, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsNotIn(List<String> values) {
            addCriterion("hero_tips not in", values, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsBetween(String value1, String value2) {
            addCriterion("hero_tips between", value1, value2, "heroTips");
            return (Criteria) this;
        }

        public Criteria andHeroTipsNotBetween(String value1, String value2) {
            addCriterion("hero_tips not between", value1, value2, "heroTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsIsNull() {
            addCriterion("melee_tips is null");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsIsNotNull() {
            addCriterion("melee_tips is not null");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsEqualTo(String value) {
            addCriterion("melee_tips =", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsNotEqualTo(String value) {
            addCriterion("melee_tips <>", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsGreaterThan(String value) {
            addCriterion("melee_tips >", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsGreaterThanOrEqualTo(String value) {
            addCriterion("melee_tips >=", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsLessThan(String value) {
            addCriterion("melee_tips <", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsLessThanOrEqualTo(String value) {
            addCriterion("melee_tips <=", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsLike(String value) {
            addCriterion("melee_tips like", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsNotLike(String value) {
            addCriterion("melee_tips not like", value, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsIn(List<String> values) {
            addCriterion("melee_tips in", values, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsNotIn(List<String> values) {
            addCriterion("melee_tips not in", values, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsBetween(String value1, String value2) {
            addCriterion("melee_tips between", value1, value2, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andMeleeTipsNotBetween(String value1, String value2) {
            addCriterion("melee_tips not between", value1, value2, "meleeTips");
            return (Criteria) this;
        }

        public Criteria andSkillListIsNull() {
            addCriterion("skill_list is null");
            return (Criteria) this;
        }

        public Criteria andSkillListIsNotNull() {
            addCriterion("skill_list is not null");
            return (Criteria) this;
        }

        public Criteria andSkillListEqualTo(String value) {
            addCriterion("skill_list =", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListNotEqualTo(String value) {
            addCriterion("skill_list <>", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListGreaterThan(String value) {
            addCriterion("skill_list >", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListGreaterThanOrEqualTo(String value) {
            addCriterion("skill_list >=", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListLessThan(String value) {
            addCriterion("skill_list <", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListLessThanOrEqualTo(String value) {
            addCriterion("skill_list <=", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListLike(String value) {
            addCriterion("skill_list like", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListNotLike(String value) {
            addCriterion("skill_list not like", value, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListIn(List<String> values) {
            addCriterion("skill_list in", values, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListNotIn(List<String> values) {
            addCriterion("skill_list not in", values, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListBetween(String value1, String value2) {
            addCriterion("skill_list between", value1, value2, "skillList");
            return (Criteria) this;
        }

        public Criteria andSkillListNotBetween(String value1, String value2) {
            addCriterion("skill_list not between", value1, value2, "skillList");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceIsNull() {
            addCriterion("equip_choice is null");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceIsNotNull() {
            addCriterion("equip_choice is not null");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceEqualTo(String value) {
            addCriterion("equip_choice =", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceNotEqualTo(String value) {
            addCriterion("equip_choice <>", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceGreaterThan(String value) {
            addCriterion("equip_choice >", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceGreaterThanOrEqualTo(String value) {
            addCriterion("equip_choice >=", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceLessThan(String value) {
            addCriterion("equip_choice <", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceLessThanOrEqualTo(String value) {
            addCriterion("equip_choice <=", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceLike(String value) {
            addCriterion("equip_choice like", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceNotLike(String value) {
            addCriterion("equip_choice not like", value, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceIn(List<String> values) {
            addCriterion("equip_choice in", values, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceNotIn(List<String> values) {
            addCriterion("equip_choice not in", values, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceBetween(String value1, String value2) {
            addCriterion("equip_choice between", value1, value2, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andEquipChoiceNotBetween(String value1, String value2) {
            addCriterion("equip_choice not between", value1, value2, "equipChoice");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroIsNull() {
            addCriterion("partner_hero is null");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroIsNotNull() {
            addCriterion("partner_hero is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroEqualTo(String value) {
            addCriterion("partner_hero =", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroNotEqualTo(String value) {
            addCriterion("partner_hero <>", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroGreaterThan(String value) {
            addCriterion("partner_hero >", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroGreaterThanOrEqualTo(String value) {
            addCriterion("partner_hero >=", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroLessThan(String value) {
            addCriterion("partner_hero <", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroLessThanOrEqualTo(String value) {
            addCriterion("partner_hero <=", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroLike(String value) {
            addCriterion("partner_hero like", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroNotLike(String value) {
            addCriterion("partner_hero not like", value, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroIn(List<String> values) {
            addCriterion("partner_hero in", values, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroNotIn(List<String> values) {
            addCriterion("partner_hero not in", values, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroBetween(String value1, String value2) {
            addCriterion("partner_hero between", value1, value2, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andPartnerHeroNotBetween(String value1, String value2) {
            addCriterion("partner_hero not between", value1, value2, "partnerHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroIsNull() {
            addCriterion("be_restrained_hero is null");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroIsNotNull() {
            addCriterion("be_restrained_hero is not null");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroEqualTo(String value) {
            addCriterion("be_restrained_hero =", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroNotEqualTo(String value) {
            addCriterion("be_restrained_hero <>", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroGreaterThan(String value) {
            addCriterion("be_restrained_hero >", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroGreaterThanOrEqualTo(String value) {
            addCriterion("be_restrained_hero >=", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroLessThan(String value) {
            addCriterion("be_restrained_hero <", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroLessThanOrEqualTo(String value) {
            addCriterion("be_restrained_hero <=", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroLike(String value) {
            addCriterion("be_restrained_hero like", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroNotLike(String value) {
            addCriterion("be_restrained_hero not like", value, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroIn(List<String> values) {
            addCriterion("be_restrained_hero in", values, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroNotIn(List<String> values) {
            addCriterion("be_restrained_hero not in", values, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroBetween(String value1, String value2) {
            addCriterion("be_restrained_hero between", value1, value2, "beRestrainedHero");
            return (Criteria) this;
        }

        public Criteria andBeRestrainedHeroNotBetween(String value1, String value2) {
            addCriterion("be_restrained_hero not between", value1, value2, "beRestrainedHero");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_infos
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 31 00:27:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}