package org.minions.common.model.kafka;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   英雄信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hero_infos
 */
public class HeroInfoModel {
    /**
     * Database Column Remarks:
     *   英雄id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_id
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private Integer heroId;

    /**
     * Database Column Remarks:
     *   英雄名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_name
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroName;

    /**
     * Database Column Remarks:
     *   英雄昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_nickname
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroNickname;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroImg;

    /**
     * Database Column Remarks:
     *   类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_type
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroType;

    /**
     * Database Column Remarks:
     *   故事
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_story
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroStory;

    /**
     * Database Column Remarks:
     *   难度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_levels
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroLevels;

    /**
     * Database Column Remarks:
     *   金币价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_gold_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private BigDecimal heroGoldPrice;

    /**
     * Database Column Remarks:
     *   点券价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_ticket_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private BigDecimal heroTicketPrice;

    /**
     * Database Column Remarks:
     *   钻石价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_diamond_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private BigDecimal heroDiamondPrice;

    /**
     * Database Column Remarks:
     *   推荐生存技能
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.recommend_summoner_skill
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String recommendSummonerSkill;

    /**
     * Database Column Remarks:
     *   推荐铭文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.rec_inscriptions
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String recInscriptions;

    /**
     * Database Column Remarks:
     *   皮肤图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.skin_imgs
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String skinImgs;

    /**
     * Database Column Remarks:
     *   大图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.big_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String bigImg;

    /**
     * Database Column Remarks:
     *   历史介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.history_intro
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String historyIntro;

    /**
     * Database Column Remarks:
     *   技能提示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String skillTips;

    /**
     * Database Column Remarks:
     *   推荐技能升级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.recommend_summoner_skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String recommendSummonerSkillTips;

    /**
     * Database Column Remarks:
     *   英雄提示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.hero_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String heroTips;

    /**
     * Database Column Remarks:
     *   生存提示
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.melee_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String meleeTips;

    /**
     * Database Column Remarks:
     *   技能
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.skill_list
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String skillList;

    /**
     * Database Column Remarks:
     *   装备介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.equip_choice
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String equipChoice;

    /**
     * Database Column Remarks:
     *   关联英雄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.partner_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String partnerHero;

    /**
     * Database Column Remarks:
     *   克制英雄
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_infos.be_restrained_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    private String beRestrainedHero;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public HeroInfoModel(Integer heroId, String heroName, String heroNickname, String heroImg, String heroType, String heroStory, String heroLevels, BigDecimal heroGoldPrice, BigDecimal heroTicketPrice, BigDecimal heroDiamondPrice, String recommendSummonerSkill, String recInscriptions, String skinImgs, String bigImg, String historyIntro, String skillTips, String recommendSummonerSkillTips, String heroTips, String meleeTips, String skillList, String equipChoice, String partnerHero, String beRestrainedHero) {
        this.heroId = heroId;
        this.heroName = heroName;
        this.heroNickname = heroNickname;
        this.heroImg = heroImg;
        this.heroType = heroType;
        this.heroStory = heroStory;
        this.heroLevels = heroLevels;
        this.heroGoldPrice = heroGoldPrice;
        this.heroTicketPrice = heroTicketPrice;
        this.heroDiamondPrice = heroDiamondPrice;
        this.recommendSummonerSkill = recommendSummonerSkill;
        this.recInscriptions = recInscriptions;
        this.skinImgs = skinImgs;
        this.bigImg = bigImg;
        this.historyIntro = historyIntro;
        this.skillTips = skillTips;
        this.recommendSummonerSkillTips = recommendSummonerSkillTips;
        this.heroTips = heroTips;
        this.meleeTips = meleeTips;
        this.skillList = skillList;
        this.equipChoice = equipChoice;
        this.partnerHero = partnerHero;
        this.beRestrainedHero = beRestrainedHero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_infos
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public HeroInfoModel() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_id
     *
     * @return the value of hero_infos.hero_id
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public Integer getHeroId() {
        return heroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_id
     *
     * @param heroId the value for hero_infos.hero_id
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroId(Integer heroId) {
        this.heroId = heroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_name
     *
     * @return the value of hero_infos.hero_name
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroName() {
        return heroName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_name
     *
     * @param heroName the value for hero_infos.hero_name
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroName(String heroName) {
        this.heroName = heroName == null ? null : heroName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_nickname
     *
     * @return the value of hero_infos.hero_nickname
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroNickname() {
        return heroNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_nickname
     *
     * @param heroNickname the value for hero_infos.hero_nickname
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroNickname(String heroNickname) {
        this.heroNickname = heroNickname == null ? null : heroNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_img
     *
     * @return the value of hero_infos.hero_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroImg() {
        return heroImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_img
     *
     * @param heroImg the value for hero_infos.hero_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroImg(String heroImg) {
        this.heroImg = heroImg == null ? null : heroImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_type
     *
     * @return the value of hero_infos.hero_type
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroType() {
        return heroType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_type
     *
     * @param heroType the value for hero_infos.hero_type
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroType(String heroType) {
        this.heroType = heroType == null ? null : heroType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_story
     *
     * @return the value of hero_infos.hero_story
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroStory() {
        return heroStory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_story
     *
     * @param heroStory the value for hero_infos.hero_story
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroStory(String heroStory) {
        this.heroStory = heroStory == null ? null : heroStory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_levels
     *
     * @return the value of hero_infos.hero_levels
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroLevels() {
        return heroLevels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_levels
     *
     * @param heroLevels the value for hero_infos.hero_levels
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroLevels(String heroLevels) {
        this.heroLevels = heroLevels == null ? null : heroLevels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_gold_price
     *
     * @return the value of hero_infos.hero_gold_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public BigDecimal getHeroGoldPrice() {
        return heroGoldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_gold_price
     *
     * @param heroGoldPrice the value for hero_infos.hero_gold_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroGoldPrice(BigDecimal heroGoldPrice) {
        this.heroGoldPrice = heroGoldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_ticket_price
     *
     * @return the value of hero_infos.hero_ticket_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public BigDecimal getHeroTicketPrice() {
        return heroTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_ticket_price
     *
     * @param heroTicketPrice the value for hero_infos.hero_ticket_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroTicketPrice(BigDecimal heroTicketPrice) {
        this.heroTicketPrice = heroTicketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_diamond_price
     *
     * @return the value of hero_infos.hero_diamond_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public BigDecimal getHeroDiamondPrice() {
        return heroDiamondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_diamond_price
     *
     * @param heroDiamondPrice the value for hero_infos.hero_diamond_price
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroDiamondPrice(BigDecimal heroDiamondPrice) {
        this.heroDiamondPrice = heroDiamondPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.recommend_summoner_skill
     *
     * @return the value of hero_infos.recommend_summoner_skill
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getRecommendSummonerSkill() {
        return recommendSummonerSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.recommend_summoner_skill
     *
     * @param recommendSummonerSkill the value for hero_infos.recommend_summoner_skill
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setRecommendSummonerSkill(String recommendSummonerSkill) {
        this.recommendSummonerSkill = recommendSummonerSkill == null ? null : recommendSummonerSkill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.rec_inscriptions
     *
     * @return the value of hero_infos.rec_inscriptions
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getRecInscriptions() {
        return recInscriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.rec_inscriptions
     *
     * @param recInscriptions the value for hero_infos.rec_inscriptions
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setRecInscriptions(String recInscriptions) {
        this.recInscriptions = recInscriptions == null ? null : recInscriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.skin_imgs
     *
     * @return the value of hero_infos.skin_imgs
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getSkinImgs() {
        return skinImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.skin_imgs
     *
     * @param skinImgs the value for hero_infos.skin_imgs
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setSkinImgs(String skinImgs) {
        this.skinImgs = skinImgs == null ? null : skinImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.big_img
     *
     * @return the value of hero_infos.big_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getBigImg() {
        return bigImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.big_img
     *
     * @param bigImg the value for hero_infos.big_img
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setBigImg(String bigImg) {
        this.bigImg = bigImg == null ? null : bigImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.history_intro
     *
     * @return the value of hero_infos.history_intro
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHistoryIntro() {
        return historyIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.history_intro
     *
     * @param historyIntro the value for hero_infos.history_intro
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHistoryIntro(String historyIntro) {
        this.historyIntro = historyIntro == null ? null : historyIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.skill_tips
     *
     * @return the value of hero_infos.skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getSkillTips() {
        return skillTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.skill_tips
     *
     * @param skillTips the value for hero_infos.skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setSkillTips(String skillTips) {
        this.skillTips = skillTips == null ? null : skillTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.recommend_summoner_skill_tips
     *
     * @return the value of hero_infos.recommend_summoner_skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getRecommendSummonerSkillTips() {
        return recommendSummonerSkillTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.recommend_summoner_skill_tips
     *
     * @param recommendSummonerSkillTips the value for hero_infos.recommend_summoner_skill_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setRecommendSummonerSkillTips(String recommendSummonerSkillTips) {
        this.recommendSummonerSkillTips = recommendSummonerSkillTips == null ? null : recommendSummonerSkillTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.hero_tips
     *
     * @return the value of hero_infos.hero_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getHeroTips() {
        return heroTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.hero_tips
     *
     * @param heroTips the value for hero_infos.hero_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setHeroTips(String heroTips) {
        this.heroTips = heroTips == null ? null : heroTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.melee_tips
     *
     * @return the value of hero_infos.melee_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getMeleeTips() {
        return meleeTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.melee_tips
     *
     * @param meleeTips the value for hero_infos.melee_tips
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setMeleeTips(String meleeTips) {
        this.meleeTips = meleeTips == null ? null : meleeTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.skill_list
     *
     * @return the value of hero_infos.skill_list
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getSkillList() {
        return skillList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.skill_list
     *
     * @param skillList the value for hero_infos.skill_list
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setSkillList(String skillList) {
        this.skillList = skillList == null ? null : skillList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.equip_choice
     *
     * @return the value of hero_infos.equip_choice
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getEquipChoice() {
        return equipChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.equip_choice
     *
     * @param equipChoice the value for hero_infos.equip_choice
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setEquipChoice(String equipChoice) {
        this.equipChoice = equipChoice == null ? null : equipChoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.partner_hero
     *
     * @return the value of hero_infos.partner_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getPartnerHero() {
        return partnerHero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.partner_hero
     *
     * @param partnerHero the value for hero_infos.partner_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setPartnerHero(String partnerHero) {
        this.partnerHero = partnerHero == null ? null : partnerHero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_infos.be_restrained_hero
     *
     * @return the value of hero_infos.be_restrained_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public String getBeRestrainedHero() {
        return beRestrainedHero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_infos.be_restrained_hero
     *
     * @param beRestrainedHero the value for hero_infos.be_restrained_hero
     *
     * @mbg.generated Thu Dec 31 00:27:50 CST 2020
     */
    public void setBeRestrainedHero(String beRestrainedHero) {
        this.beRestrainedHero = beRestrainedHero == null ? null : beRestrainedHero.trim();
    }
}