package org.minions.common.model.kafka;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HeroWeaponModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public HeroWeaponModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWeaponIdIsNull() {
            addCriterion("weapon_id is null");
            return (Criteria) this;
        }

        public Criteria andWeaponIdIsNotNull() {
            addCriterion("weapon_id is not null");
            return (Criteria) this;
        }

        public Criteria andWeaponIdEqualTo(Integer value) {
            addCriterion("weapon_id =", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdNotEqualTo(Integer value) {
            addCriterion("weapon_id <>", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdGreaterThan(Integer value) {
            addCriterion("weapon_id >", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("weapon_id >=", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdLessThan(Integer value) {
            addCriterion("weapon_id <", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdLessThanOrEqualTo(Integer value) {
            addCriterion("weapon_id <=", value, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdIn(List<Integer> values) {
            addCriterion("weapon_id in", values, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdNotIn(List<Integer> values) {
            addCriterion("weapon_id not in", values, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdBetween(Integer value1, Integer value2) {
            addCriterion("weapon_id between", value1, value2, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponIdNotBetween(Integer value1, Integer value2) {
            addCriterion("weapon_id not between", value1, value2, "weaponId");
            return (Criteria) this;
        }

        public Criteria andWeaponNameIsNull() {
            addCriterion("weapon_name is null");
            return (Criteria) this;
        }

        public Criteria andWeaponNameIsNotNull() {
            addCriterion("weapon_name is not null");
            return (Criteria) this;
        }

        public Criteria andWeaponNameEqualTo(String value) {
            addCriterion("weapon_name =", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameNotEqualTo(String value) {
            addCriterion("weapon_name <>", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameGreaterThan(String value) {
            addCriterion("weapon_name >", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameGreaterThanOrEqualTo(String value) {
            addCriterion("weapon_name >=", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameLessThan(String value) {
            addCriterion("weapon_name <", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameLessThanOrEqualTo(String value) {
            addCriterion("weapon_name <=", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameLike(String value) {
            addCriterion("weapon_name like", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameNotLike(String value) {
            addCriterion("weapon_name not like", value, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameIn(List<String> values) {
            addCriterion("weapon_name in", values, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameNotIn(List<String> values) {
            addCriterion("weapon_name not in", values, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameBetween(String value1, String value2) {
            addCriterion("weapon_name between", value1, value2, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponNameNotBetween(String value1, String value2) {
            addCriterion("weapon_name not between", value1, value2, "weaponName");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceIsNull() {
            addCriterion("weapon_price is null");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceIsNotNull() {
            addCriterion("weapon_price is not null");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceEqualTo(BigDecimal value) {
            addCriterion("weapon_price =", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceNotEqualTo(BigDecimal value) {
            addCriterion("weapon_price <>", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceGreaterThan(BigDecimal value) {
            addCriterion("weapon_price >", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("weapon_price >=", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceLessThan(BigDecimal value) {
            addCriterion("weapon_price <", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("weapon_price <=", value, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceIn(List<BigDecimal> values) {
            addCriterion("weapon_price in", values, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceNotIn(List<BigDecimal> values) {
            addCriterion("weapon_price not in", values, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weapon_price between", value1, value2, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("weapon_price not between", value1, value2, "weaponPrice");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeIsNull() {
            addCriterion("weapon_type is null");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeIsNotNull() {
            addCriterion("weapon_type is not null");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeEqualTo(String value) {
            addCriterion("weapon_type =", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeNotEqualTo(String value) {
            addCriterion("weapon_type <>", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeGreaterThan(String value) {
            addCriterion("weapon_type >", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeGreaterThanOrEqualTo(String value) {
            addCriterion("weapon_type >=", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeLessThan(String value) {
            addCriterion("weapon_type <", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeLessThanOrEqualTo(String value) {
            addCriterion("weapon_type <=", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeLike(String value) {
            addCriterion("weapon_type like", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeNotLike(String value) {
            addCriterion("weapon_type not like", value, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeIn(List<String> values) {
            addCriterion("weapon_type in", values, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeNotIn(List<String> values) {
            addCriterion("weapon_type not in", values, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeBetween(String value1, String value2) {
            addCriterion("weapon_type between", value1, value2, "weaponType");
            return (Criteria) this;
        }

        public Criteria andWeaponTypeNotBetween(String value1, String value2) {
            addCriterion("weapon_type not between", value1, value2, "weaponType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_weapon
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 31 00:41:22 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hero_weapon
     *
     * @mbg.generated Thu Dec 31 00:41:22 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}