server:
  port: 8081

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minions?currentSchema=kafka
    username: minions
    password: postgres
  application:
    name: minions-kafka
  data:
    mongodb:
      uri: mongodb://admin:mongo@localhost:27017/admin

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/test

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      retries: 3
      batch-size: 323804
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      group-id: minions
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 1

minions:
  spider:
    host: localhost
    port: 6800
    project: default
