server:
  port: 8081

logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG

mybatis:
  type-aliases-package: org.minions.common.moedel.demo
  mapper-locations:
    - classpath:mapper/*Mapper.xml

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.minions.org:5432/minions?currentSchema=kafka
    username: minions
    password: postgres
  application:
    name: minions-demo
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    mongodb:
      uri: mongodb://admin:mongo@mongo.minions.org:27017/admin

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      retries: 3
      batch-size: 323804
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      group-id: minions
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 1
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      concurrency: 1



minions:
  spider:
    host: spider.minions.org
    port: 6800
    project: test